### ISSUE TITLE
Dropdown：初始化时闪烁

### ISSUE THREAD

**Issue by nuysoft** [thx/brix-components#16]
全局设置 `<select>` 的样式：
```css
select[bx-name="components/dropdown"] {
    visibility: hidden;
}
```
