### ISSUE TITLE
Table Column RWD：翻页按钮遮挡表头字段

### ISSUE THREAD

**Issue by nuysoft** [thx/brix-components#67]
每页第一列加样式 `.start`，最后一列加样式 `.end`
```css
th.end {
    padding-right: 40px;
}
```
