### ISSUE TITLE
Uploader：支持没有 form 的场景

### ISSUE THREAD

**Issue by nuysoft** [thx/brix-components#90]
```js
var form = $relatedElement[0].form
if (!form) {
    $relatedElement.wrap('<form class="uploader-ghost-form">')
    form = $relatedElement[0].form
}
```

```css
.uploader-ghost-form {
    position: static;
    width: 0;
    height: 0;
    opacity: 0;
    cursor: pointer;
    margin: 0;
    padding: 0;
    border: none;
    box-shadow: none;
}
```

**注意：**
如果自动在组件外包裹一层 `<form>`，可能会导致不符合预期的样式布局。
